name: Call Security Scans and Docker Build-Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  security-scans:
    name: Run Security Scans
    uses: rameshlodh/security/.github/workflows/security.yml@main
    secrets:
      SEMGREP_TOKEN: ${{ secrets.SEMGREP_TOKEN }}

  docker-build-push:
    name: Run Docker Workflow
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event_name == 'pull_request'
    needs: security-scans
    uses: rameshlodh/container/.github/workflows/container.yml@main
    with:
      application_name: 'application'
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
