name: Call Security Scans and Docker Build-Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scans:
    name: Run Security Scans
    uses: rameshlodh/security/.github/workflows/security.yml@main
    secrets:
      SEMGREP_TOKEN: ${{ secrets.SEMGREP_TOKEN }}

  docker-build-push:
    name: Docker Build and Push
    needs: security-scans  # Ensures this job runs only if security-scans succeed
    uses: rameshlodh/container/.github/workflows/container.yml@main
    with:
      application_name: 'application'  # Application name passed to the reusable workflow
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
