name: Call Security Scans Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scans:
    needs: docker-build-push
    uses: rameshlodh/security/.github/workflows/security.yml@main
    secrets:
      SEMGREP_TOKEN: ${{ secrets.SEMGREP_TOKEN }}

  docker-build-push:
    name: Docker Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # - name: Build Docker Image
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/application:latest .

      # - name: Push Docker Image
      #   run: |
      #     docker push ${{ secrets.DOCKER_HUB_USERNAME }}/application:latest


